services:

  agent-flow:
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/agent/config.river
    environment:
      - AGENT_MODE=flow
    image: grafana/agent:latest
    ports:
      - 12345:12345
    volumes:
      - ./agent-flow.river:/etc/agent/config.river:ro
      - /run/docker.sock:/run/docker.sock:ro

  grafana:
    image: grafana/grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Editor
      - GF_AUTH_DISABLE_LOGIN_FORM=false
    ports:
      - 3000:3000
    volumes:
      - ./grafana.yaml:/etc/grafana/provisioning/datasources/mimir.yaml

  mimir:
    command:
      - --config.file=/etc/mimir/demo.yaml
    image: grafana/mimir:latest
    ports:
      - 9009:9009
    volumes:
      - ./mimir.yaml:/etc/mimir/demo.yaml:ro
